---
- hosts: localhost
  gather_facts: false
  vars_files:
    - ./inventory/group_vars/all/vault_variables.yaml
  tasks:
  
    - name: Gather the old version of the application
      ansible.builtin.shell:
       cmd: "{{ bash_command_for_image_version }}"
      register: old_image_version

    - name: Bump the version of the application with maven
      ansible.builtin.shell:
       cmd: "{{ mvnw_command_version_update }}"
       chdir: "{{ application_directory }}"

    - name: Gather the new version of the application
      ansible.builtin.shell:
       cmd: "{{ bash_command_for_image_version }}"
      register: new_image_version
    
    - set_fact:
        new_image_version: "{{new_image_version.stdout}}"

    # - name: Git add all changed files
    #   ansible.builtin.shell:
    #     cmd: "{{ git_add_command}}{{ filename_to_be_added_to_git }}"
    #   vars:
    #     ansible_become: false

    # - name: Perform a git commit
    #   ansible.builtin.shell:
    #     cmd: "{{ git_commit_command }} '{{ git_commit_command_comment }}:{{ new_image_version.stdout }}'"
    #   vars:
    #     ansible_become: false

    # - name: Perform a git tag
    #   ansible.builtin.shell:
    #     cmd: "{{ git_tag_command }} v{{ new_image_version.stdout }} {{ git_tag_command_end }}"
    #   vars: 
    #     ansible_become: false

    # - name: Perform a git push
    #   ansible.builtin.shell:
    #     cmd: "{{ git_push_command }}{{ git_branch_name }}"
    #   vars:
    #     ansible_become: false

    - name: Create the jar file
      ansible.builtin.shell:
        cmd: "{{ mvnw_command_package }}"
        chdir: "{{ application_directory }}"
      retries: 5
      delay: 20

    - name: Check if the jar file has been created
      ansible.builtin.stat:
        path: "{{ package_location }}{{ new_image_version }}-SNAPSHOT.jar"
      register: jarFileCheck
   
    - name: Attempt to create the jar file again, if it doesn't exist
      ansible.builtin.shell:
        cmd: "{{ mvnw_command_package }}"
        chdir: "{{ application_directory }}"
      retries: 5
      delay: 20
      when: 
        - jarFileCheck.stat.exists != true

    - name: Update the docker file with the new jar file name
      ansible.builtin.lineinfile:
        path: "{{ docker_file_name }}"
        regexp: '^COPY target/api_server-[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}-SNAPSHOT\.jar app\.jar'
        line: 'COPY target/api_server-{{ new_image_version }}-SNAPSHOT.jar app.jar'
    
  

